import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/providers/query-providers";
import { SheetProvider } from "@/providers/sheet-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import Header from "./_components/header";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
  >
    <html lang="en">
      <body
        className={`antialiased dotted-background`}
      >
        <Header />
        <QueryProvider>
          <SheetProvider />
          <Toaster />
        {children}
        </QueryProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
